//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace MikeWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        [Required]
        [StringLength(500, ErrorMessage = "The {0} must be at between {2} and {1} characters.", MinimumLength = 1)]
        [Display(Name = "Message")]
        public string Message { get; set; }
        public string AuthorUserName { get; set; }
    }
}
